# Config Plugin Time Handler
# Relry Pereira dos Santos
# version: 1.0
# 
# Property for plugin
# 

check-update-plugin: true
ticks-check-update-worlds: 40
default-language: en_US # configuration without effect yet (soon)

# configure where day and night start for the server
# used to configure the duration of day and night
day-begin-in: 23000   # configuration without effect yet (soon)
night-begin-in: 13000 # configuration without effect yet (soon)
