name: TimeHandler
version: 1.4.1-beta
main: me.reratos.timehandler.TimeHandler
author: Relry
database: false
website: https://www.spigotmc.org/resources/timehandler.83803/
description: >
   It allows manipulating the time of the worlds and / or setting a condition for it.
   Define duration (in ticks) of the day and night, define the phase of the moon..

commands:
    timehandler:
        description: Time Handler plugin to manipulate the time of the server worlds.
        aliases: [th]
        permission: timehandler.use
        usage: /timehandler <action>
    "timehandler info":
        description: Command to check the configuration of the world in the time handler.
        aliases: ["th info"]
        permission: timehandler.info.use
        usage: /timehandler info [world]
    "timehandler help":
        description: Command to list the timehandler plugin commands.
        aliases: ["th help"]
        permission: timehandler.help.use
        usage: /timehandler help [comando]
    "timehandler list":
        description: Command to list the worlds configured in the timehandler.
        aliases: ["th list"]
        permission: timehandler.list.use
        usage: /timehandler list
    "timehandler set":
        description: Command to configure the world in the timehandler.
        aliases: ["th set"]
        permission: timehandler.set.use
        usage: /timehandler set <world> [<property> <value>]
    "timehandler update":
        description: Command to check update available for the plugin.
        aliases: ["th update"]
        permission: timehandler.update.use
        usage: /timehandler update
    day:
        description: Command to set world time to 500 cycles (day).
        aliases: [thd]
        permission: timehandler.time.use
        usage: /day [world]
    night:
        description: Command to set world time to 14000 cycles (night).
        aliases: [thn]
        permission: timehandler.time.use
        usage: /night [world]
    moonPhase:
        description: Command to set phase of the moon.
        aliases: [thmp]
        permission: timehandler.weather.use
        usage: /moonPhase <phase> [world]
    rain:
        description: Command to set the weather of the world for rainy.
        aliases: [thr]
        permission: timehandler.weather.use
        usage: /rain [world]
    thundering:
        description: Command to set the weather of the world for storm.
        aliases: [tht]
        permission: timehandler.weather.use
        usage: /thundering [world]
    calm:
        description: Command to set world time to calm (no rain).
        aliases: [thc]
        permission: timehandler.weather.use
        usage: /calm [world]

permissions:
    timehandler.*:
        description: Gives access to use the TimeHandler plugin commands.
        default: op
        children:
            timehandler.info.use: true
            timehandler.help.use: true
            timehandler.list.use: true
            timehandler.update.use: true
#            timehandler.remove.use: true
            timehandler.set.use: true
            timehandler.time.use: true
            timehandler.weather.use: true
    timehandler.info.use:
        description: Gives access to view world information in the TimeHandler plugin.
        default: op
    timehandler.help.use:
        description: Gives access to see the list of commands for the TimeHandler plugin.
        default: op
    timehandler.list.use:
        description: Gives access to see the list of worlds already configured in the TimeHandler plugin.
        default: op
    timehandler.update.use:
        description: Gives access to check for updates to the TimeHandler plugin.
        default: op
    timehandler.set.use:
        description: Gives access to configure world in the TimeHandler plugin.
        default: op
    timehandler.time.use:
        description: Gives access to change the time of the world to day or night.
        default: op
    timehandler.weather.use:
        description: Gives access to change the weather in the world to rainy or calm.
        default: op
        
